{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_module_demo",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 15221929,
          "sha512": "3073739fd3b522142b767cfe58e15091d0ab33462c6e7ec5e2f1f7f81262ca5f919a9ef796a67558463cbb9f8fd9daa6a952a1188a10656ba1702b631f55b8bc",
          "sha256": "e2e13ee8d6c91e19d8af0c44451478d866ae2c29769909f75eceaf34c7eb06dd",
          "sha1": "424e5e41c030bf1164096a0e72f853a2969a74f3",
          "md5": "e820efdd66c53547343fe3f50fcd3db0"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 15221929,
          "sha512": "3073739fd3b522142b767cfe58e15091d0ab33462c6e7ec5e2f1f7f81262ca5f919a9ef796a67558463cbb9f8fd9daa6a952a1188a10656ba1702b631f55b8bc",
          "sha256": "e2e13ee8d6c91e19d8af0c44451478d866ae2c29769909f75eceaf34c7eb06dd",
          "sha1": "424e5e41c030bf1164096a0e72f853a2969a74f3",
          "md5": "e820efdd66c53547343fe3f50fcd3db0"
        }
      ]
    }
  ]
}
