{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_module_demo",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 4801955,
          "sha512": "81dd1777f116e1df7005697ffb6bb4195270d5f733f36ed532e19a3d31866b169adec93cb6cb3e8649ec8527d09fe2458253d4261978c4221aecb409db177858",
          "sha256": "6315180d51b1a5c6e45b443e5a7626b019965760bdcf8a6ddc294a81b9b557c9",
          "sha1": "fd3b8af30a736ae7561231f49fdfbad499029be4",
          "md5": "0e8ebd007bce8f2f8046df478b601051"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 4801955,
          "sha512": "81dd1777f116e1df7005697ffb6bb4195270d5f733f36ed532e19a3d31866b169adec93cb6cb3e8649ec8527d09fe2458253d4261978c4221aecb409db177858",
          "sha256": "6315180d51b1a5c6e45b443e5a7626b019965760bdcf8a6ddc294a81b9b557c9",
          "sha1": "fd3b8af30a736ae7561231f49fdfbad499029be4",
          "md5": "0e8ebd007bce8f2f8046df478b601051"
        }
      ]
    }
  ]
}
