{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_module_demo",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 7326261,
          "sha512": "eabb2968640696e3ec46b4b642444346c77e78cc4e57e67c9241b2994e9fcbdcf06640fba9d6b220fff5c7eac6344a7b4901e9e785c4a300eeee5ee11408e49e",
          "sha256": "2b8b0d047406bc1ee0f3e9297cf8d16e4ecd808059351f7abc51c18cdb35339d",
          "sha1": "60e3fda291e8d1a2d086d75eb7938a16290f949b",
          "md5": "ba8e6f7ed15399bea239a8e44eef60fe"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-4a585b79294e830fa89c24924d58a27cc8fbf406"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 7326261,
          "sha512": "eabb2968640696e3ec46b4b642444346c77e78cc4e57e67c9241b2994e9fcbdcf06640fba9d6b220fff5c7eac6344a7b4901e9e785c4a300eeee5ee11408e49e",
          "sha256": "2b8b0d047406bc1ee0f3e9297cf8d16e4ecd808059351f7abc51c18cdb35339d",
          "sha1": "60e3fda291e8d1a2d086d75eb7938a16290f949b",
          "md5": "ba8e6f7ed15399bea239a8e44eef60fe"
        }
      ]
    }
  ]
}
